spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: microconfig-test-client

eureka:
 client:
  service-url:
    defaultZone: http://admin:admin@eureka-1:7001/eureka,http://admin:admin@eureka-2:7002/eureka,http://admin:admin@eureka-3:7003/eureka
---
server:
  port: 8102

spring:
  profiles: test
  application:
      name: microconfig-test-client

eureka:
 client:
  service-url:
    defaultZone: http://admin:admin@eureka-1:7001/eureka,http://admin:admin@eureka-2:7002/eureka,http://admin:admin@eureka-3:7003/eureka
