spring:
  profiles:
    active:
      - dev
---
server:
 port: 8080

mybatis:
 # 所有的mapper映射文件
 mapper-locations:
 - classpath:mapping/*.xml
 # 所有Entity别名类所在包
 type-aliases-package: com.cr.entity
 # 开启数据库字段与类属性驼峰命名与下划线转换
 configuration:
   map-underscore-to-camel-case: true

spring:
 profiles: dev
 application:
   # 注册进Eureka的微服务名
   name: microcloud-provider-config-product
 datasource:
   # 配置当前要使用的数据源的操作类型
   type: com.alibaba.druid.pool.DruidDataSource
   # 配置MySQL的驱动程序类
   #   driver-class-name: com.mysql.jdbc.Driver
   driver-class-name: com.mysql.jdbc.Driver
   # 数据库连接地址
   url: jdbc:mysql://localhost:3306/clouddb01?serverTimezone=GMT%2B8
   # 数据库用户名
   username: root
   # 数据库连接密码
   password: admin
# security:
#    user:
#      name: admin  # 认证用户名
#      password: admin  # 认证密码
#      roles:
#       - USER # 授权角色
logging:
  level:
    com.cr: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    # 客户端进行Eureka注册的配置
    register-with-eureka: true
    service-url:
#      defaultZone: http://admin:admin@localhost:7001/eureka
      defaultZone: http://admin:admin@eureka-1:7001/eureka,http://admin:admin@eureka-2:7002/eureka,http://admin:admin@eureka-3:7003/eureka
  instance:
    instance-id: product-8080
    # 访问路径可以显示IP地址
    prefer-ip-address: true
#    # 设置心跳的时间间隔（默认是30秒）
#    lease-renewal-interval-in-seconds: 2
#    # 如果现在超过了5秒的间隔（默认是90秒）
#    lease-expiration-duration-in-seconds: 5

# 监控信息
info:
  app.name: microcloud-provider-hystrix-product
  company.name: cr
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

 
---
server:
 port: 8090

mybatis:
 # 所有的mapper映射文件
 mapper-locations:
 - classpath:mapping/*.xml
 # 所有Entity别名类所在包
 type-aliases-package: com.cr.entity
 # 开启数据库字段与类属性驼峰命名与下划线转换
 configuration:
   map-underscore-to-camel-case: true

spring:
 profiles: test
 application:
   # 注册进Eureka的微服务名
   name: microcloud-provider-config-product
 datasource:
   # 配置当前要使用的数据源的操作类型
   type: com.alibaba.druid.pool.DruidDataSource
   # 配置MySQL的驱动程序类
   #   driver-class-name: com.mysql.jdbc.Driver
   driver-class-name: com.mysql.jdbc.Driver
   # 数据库连接地址
   url: jdbc:mysql://localhost:3306/clouddb01?serverTimezone=GMT%2B8
   # 数据库用户名
   username: root
   # 数据库连接密码
   password: admin
# security:
#    user:
#      name: admin  # 认证用户名
#      password: admin  # 认证密码
#      roles:
#       - USER # 授权角色
logging:
  level:
    com.cr: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    # 客户端进行Eureka注册的配置
    register-with-eureka: true
    service-url:
#      defaultZone: http://admin:admin@localhost:7001/eureka
      defaultZone: http://admin:admin@eureka-1:7001/eureka,http://admin:admin@eureka-2:7002/eureka,http://admin:admin@eureka-3:7003/eureka
  instance:
    instance-id: product-8090
    # 访问路径可以显示IP地址
    prefer-ip-address: true
#    # 设置心跳的时间间隔（默认是30秒）
#    lease-renewal-interval-in-seconds: 2
#    # 如果现在超过了5秒的间隔（默认是90秒）
#    lease-expiration-duration-in-seconds: 5

# 监控信息
info:
  app.name: microcloud-provider-hystrix-product
  company.name: cr
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$


